version: 2
jobs:
  rails-test-suite:
    docker:
      - image: ruby:2.3.1
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgis://root@localhost/tpp_datastore_test
      - image: mdillon/postgis:9.5
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: tpp_datastore_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - tpp-datastore-{{ checksum "Gemfile.lock" }}
            - tpp-datastore-
      - run:
          name: Install dependencies
          command: apt-get update -qq && apt-get install -y libgeos-dev libproj-dev
      - run:
          name: Install bundle
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - save_cache:
          key: tpp-datastore-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Database setup
          command: bundle exec rake db:drop db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rake
      # - run:
      #     name: Run profile
      #     command: mkdir -p $CIRCLE_ARTIFACTS/profiling && bundle exec rake profile:import:nycdot[$CIRCLE_ARTIFACTS/profiling]
  build-container-image:
    docker:
      - image: circleci/buildpack-deps:16.04-curl
    steps:
      - checkout
      - run: sudo apt-get update -qq && sudo apt-get install python-pip python-dev -y
      - setup_remote_docker
      - run: docker build -t tpp_banco_de_dados:${CIRCLE_TAG:-$CIRCLE_BRANCH} .
      - run: docker tag tpp_banco_de_dados:${CIRCLE_TAG:-$CIRCLE_BRANCH}
workflows:
  version: 2
  test-and-build-workflow:
    jobs:
      - rails-test-suite:
          filters:
            tags:
              only: /.*/
      - build-container-image:
          requires:
            - rails-test-suite
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
